#!/bin/bash

# Script que compila automáticamente un archivo de LaTeX cada vez que se guarda.

# Para usarlo, ejecutar en la Terminal "sh compilatex archivo.tex" (el script y el archivo de LaTeX tienen que estar en la misma carpeta).

# Para terminar de ejecutar el script, tipear en la Terminal "Ctrl + Shift + c".

BetterPDFLaTeX(){
GREP="grep --color=always --line-buffered"
(/usr/bin/pdflatex -file-line-error $* 2>&1) \
 | $GREP -vP "^\s*((\[|\]|\(|\))\s*)+$" \
 | GREP_COLOR="01;31" $GREP -P "(^[^:]*:\d+: )|(^l\.\d+ )|(^! LaTeX Error: )|$" \
 | GREP_COLOR="00;33" $GREP -P "(LaTeX Warning(:|))|(Package [^\s]+ Warning(:|))|$" \
 | GREP_COLOR="00;32" $GREP -P "^Output written on .*\.pdf \(.*\)\.$|$" \
 | uniq
} 


BetterPDFLaTeX -interaction=nonstopmode -halt-on-error "$1"    # Compila por primera vez el archivo.
fecha=$(date -r "$1" +%T)                                      # Guarda en $fecha la hora exácta de la última modificación del archivo.


while true 
    do
       if [ "$fecha" != "$(date -r "$1" +%T)" ]; then    
            BetterPDFLaTeX -interaction=nonstopmode -halt-on-error "$1"
            fecha=$(date -r "$1" +%T)
       fi 
       sleep 1	
    done
