#!/bin/bash

# Script que compila automáticamente un archivo de LaTeX cada vez que se guarda.

# Para usarlo, ejecutar en la Terminal "sh compilatex archivoACompilar.tex" (el script y el archivo de LaTeX tienen que estar en la misma carpeta).
# Si quiero editar un archivo, pero compilar otro (ej: estoy editando caratula.tex pero quiero compilar informe.tex), hacemos: "sh compilatex informe.tex caratula.tex"

# Para terminar de ejecutar el script, tipear en la Terminal "Ctrl + Shift + c".

BetterPDFLaTeX(){
GREP="grep --color=always --line-buffered"
(/usr/bin/pdflatex -file-line-error $* 2>&1) \
 | $GREP -vP "^\s*((\[|\]|\(|\))\s*)+$" \
 | GREP_COLOR="01;31" $GREP -P "(^[^:]*:\d+: )|(^l\.\d+ )|(^! LaTeX Error: )|$" \
 | GREP_COLOR="00;33" $GREP -P "(LaTeX Warning(:|))|(Package [^\s]+ Warning(:|))|$" \
 | GREP_COLOR="00;32" $GREP -P "^Output written on .*\.pdf \(.*\)\.$|$" \
 | uniq
} 

if [ $# = 2 ]; then                                            # Si tengo 2 argumentos, entonces el archivo que estoy editando es el segundo.
	archivoAEditar="$2"	
else
        archivoAEditar="$1" 
fi

fecha=$(date -r "$archivoAEditar" +%T)                         # Guarda en $fecha la hora exácta de la última modificación del archivo que estamos editando.

BetterPDFLaTeX -interaction=nonstopmode -halt-on-error "$1"    # Compila por primera vez el archivo (siempre es el primer parámetro).

while true 
    do
       if [ "$fecha" != "$(date -r "$archivoAEditar" +%T)" ]; then    
            BetterPDFLaTeX -iteraction=nonstopmode -halt-on-error "$1"
            fecha=$(date -r "$archivoAEditar" +%T)
       fi 
       sleep 0.5
    done
